### PR TITLE
[UDN: host isolation]: fix lint

### PR DESCRIPTION
**Pull request by flavio-fernandes**
Fix issue introduced in 3275d498b4026609effbaaf88a88ff6e43819ad5

```
$ make lint
...
level=info msg="[linters_context/goanalysis] analyzers took 4m3.270244378s with top 10 stages: buildir: 2m29.130860339s, nilness: 5.955006101s, printf: 3.859331341s, fact_deprecated: 3.799388364s, ctrlflow: 3.482855272s, inspect: 3.316943625s, fact_purity: 2.391957936s, S1038: 2.121120295s, gofmt: 2.089813745s, unused: 2.075213702s" pkg/node/base_node_network_controller_dpu.go:1: : # github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node [github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.test] pkg/node/udn_isolation_test.go:364:52: not enough arguments in call to NewUDNHostIsolationManager
        have (bool, bool, "k8s.io/client-go/informers/core/v1".PodInformer)
        want (bool, bool, "k8s.io/client-go/informers/core/v1".PodInformer, string, record.EventRecorder) (typecheck)
package node
```

### CODE REVIEW

**Review by trozet — APPROVED** [review]
thanks @flavio-fernandes ! just hit this myself

@tssurya @jcaamano fyi

**Comment by trozet** [comment]
known egress ip flakes:

```
2025-02-10T21:57:18.1427555Z [38;5;9m[1mSummarizing 2 Failures:[0m
2025-02-10T21:57:18.1432176Z   [38;5;9m[FAIL][0m [0mOVN master EgressIP Operations cluster default network [38;5;243mOn node UPDATE [0m[secondary host network] should perform proper OVN transactions when namespace and pod is created after node egress label switch [38;5;9m[1m[It] interconnect enabled; node1 and node2 in global zones[0m
2025-02-10T21:57:18.1434817Z   [38;5;243m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/egressip_test.go:2060[0m
2025-02-10T21:57:18.1438029Z   [38;5;9m[FAIL][0m [0mOVN master EgressIP Operations cluster default network [38;5;243mOn node DELETE [0m[secondary host network] should perform proper OVN transactions when namespace and pod is created after node egress label switch [38;5;9m[1m[It] interconnect enabled; node1 in global and node2 in remote zones[0m
2025-02-10T21:57:18.1440940Z   [38;5;243m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/egressip_test.go:3296[0m
```

**Comment by npinaeva** [comment]
thank you @flavio-fernandes!
It must be because our tests don't re-run when new changes are merged, not sure how we can avoid this

**Comment by jcaamano** [comment]
that's weird, the tests are supposed to run with the merge

**Comment by jcaamano** [comment]
Ah that's because it was in flight with this other change at the same time. 

The solution is the merge queue.

**Comment by jcaamano** [comment]
and I didn't rebase when merging, which I should have. But it needs to be and all or nothing process, otherwise it is error prone.
